export const GET_ERROR = 'GET_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ENABLE2FA = 'SET_ENABLE2FA';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ACCOUNT = 'SET_ACCOUNT';